### ISSUE TITLE
Activity flags remaining in monomers

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/belpy#17]
Activity flags are still generated into monomer signatures, even if they don't appear in any rules. 
E.g. all rules where MAP2K1 is active, it is represented as 
MAP2K1(S218='p',S222='p'), 
but the monomer has the signature
Monomer(u'MAP2K1', ['S218', 'S222', 'Kinase', 'Active'], {'Active': ['inactive', 'active'], 'S218': ['u', 'p'], 'Kinase': ['inactive', 'active'], 'S222': ['u', 'p']})

**Comment by johnbachman** [comment]
For phosphorylations at least (which is the only place where we compile out the activity flag using activating modifications) this should be trivial--I will make the change to the monomers_one_step method.

**Comment by johnbachman** [comment]
By the way, what kind of statement is producing an "Active" site in addition to a "Kinase" site?

**Comment by bgyori** [comment]
Doesn't it somehow come from activity modifications?

**Comment by johnbachman** [comment]
Indeed, in a line bracketed by FIXME FIXME FIXME :) If only I could remember the issue there. I think it can just be deleted.
