### ISSUE TITLE
Protein names containing hyphens cause an error in the BioPax API

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/belpy#19]
For example, the protein name RAF1-BRAF is propagated through the PysbAssembler and into the PySB model, where it triggers an InvalidComponentNameError, e.g.

bp = biopax_api.process_pc_neighborhood(['BRAF'])
bp.get_phosphorylation()
pa.add_statements(bp.statements)
pa.make_model()
...
InvalidComponentNameError: Not a valid component name: 'RAF1-BRAF'

**Comment by bgyori** [comment]
Component names in pysb are checked as follows:
```
if not re.match(r'[_a-z][_a-z0-9]*\Z', name, re.IGNORECASE):
    raise InvalidComponentNameError(name)
```
So 'RAF-BRAF', 'MEK family' and '14-3-3' are all invalid names. One possibility is to get all the processors to generate agent names that pysb will accept. It would probably be better if we could handle this on assembly.

**Comment by johnbachman** [comment]
Well, they are currently handled in the BEL case in bel/processor.py, as part of the URI cleanup in term_from_uri:

    def term_from_uri(uri):
        """Basic conversion of RDF URIs to more friendly strings.
  
        Removes prepended URI information, and replaces spaces and hyphens with
        underscores.
        """

For consistency, we could handle this in the biopax case as well.

**Comment by johnbachman** [comment]
Perhaps the best place to handle this is in biopax/processor.py, _get_entity_names?

**Comment by johnbachman** [comment]
Note: fixed with a change to biopax/processor _get_entity_names in commit 8522649cd23e59bd65381bec3201bff4a0c1ae99
